core/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from core.views import ProfileDetailView, FeedView, LikeView, CommentView, FollowersView, FollowView, ImageDetailView, \
    VideoDetailView, AddViewsToVideo, HashTagPostListView, PlacePostListView, ImageCommentsView, AddImageView

app_name = 'core'
urlpatterns = [
    path('', FeedView.as_view(), name='feed'),
    path('profile/<username>', ProfileDetailView.as_view(), name='to_profile'),
    path('profile/<username>/followers', FollowersView.as_view(), name='to_profile_followers'),
    path('like/', LikeView.as_view(), name='like'),
    path('follow/', FollowView.as_view(), name='follow'),
    path('comment/', CommentView.as_view(), name='comment'),
    path('image/<int:pk>', ImageDetailView.as_view(), name='to_image'),
    path('video/<int:pk>', VideoDetailView.as_view(), name='to_video'),
    path('add_view/', AddViewsToVideo.as_view(), name='add_view'),
    path('hashtag/<hashtag>', HashTagPostListView.as_view(), name='hashtag'),
    path('place/<place_slug>', PlacePostListView.as_view(), name='place'),
    path('image/<int:pk>/comments', ImageCommentsView.as_view(), name='image_comments'),
    path('add/image', AddImageView.as_view(), name='add_image'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

instagram_clone_django/urls.py
from django.conf.urls import url
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, include

import core

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Api descriotion",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('message.urls')),
    path('', include('core.urls')),
    path('auth/', include('user_profile.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

handler404 = core.views.error_404
handler500 = core.views.error_500

message/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from message.api import MessageViewSet, ChatViewSet
from message.views import RoomView, RoomListView, CreateChatRoom

app_name = 'messages'

router = DefaultRouter()
router.register(r'messages', MessageViewSet, basename='message')
router.register(r'chatroom', ChatViewSet, basename='chatroom')

urlpatterns = [
    path('chats/', RoomListView.as_view(), name='chats'),
    path('<int:id>/', RoomView.as_view(), name='room'),
    path('api/', include(router.urls)),
    path('write/<username>/', CreateChatRoom.as_view(), name='write_to')
]

user_profile/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from user_profile.views import RegistrationView, LoginView, ResetPasswordRequestView, ResetPasswordView, MessageSentView

app_name = 'user_profile'
urlpatterns = [
    path('register/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('user_profile:login')), name='logout'),
    path('reset/', ResetPasswordRequestView.as_view(), name='reset_request'),
    path('reset-password/<username>/<token>', ResetPasswordView.as_view(), name='reset'),
    path('reset-message/', MessageSentView.as_view(), name='reset_redirect_message'),
]

core/models.py
from django.db import models

from core.validators import HashTagValidator
from user_profile.models import Profile


class HashTag(models.Model):
    hashtag_validator = HashTagValidator()

    hashtag = models.CharField(max_length=50, validators=[hashtag_validator], unique=True)

    def __str__(self):
        return f'{self.hashtag}'


class Place(models.Model):
    place_name = models.CharField(max_length=50)
    place_slug = models.SlugField(max_length=50)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return f'{self.place_name}'

    class Meta:
        unique_together = (('id', 'place_slug'),)
        ordering = ('place_name',)


class InstagramObject(models.Model):
    description = models.CharField(max_length=150, blank=True)
    posted_on = models.DateTimeField(auto_now_add=True)
    hashtag = models.ForeignKey(HashTag, on_delete=models.CASCADE, blank=True, null=True)
    place = models.ForeignKey(Place, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)

    class Meta:
        abstract = True


def get_user_image_folder(instance, filename):
    return f'{instance.user.username}/photos/{filename}'


def get_user_video_folder(instance, filename):
    return f'{instance.user.username}/videos/{filename}'


class Image(InstagramObject):
    image_obj = models.ImageField(upload_to=get_user_image_folder)
    likes = models.ManyToManyField(Profile, blank=True, related_name='image_liked_by')

    def __str__(self):
        return f'{self.user} {self.description} {self.posted_on} image'


class Video(InstagramObject):
    video_obj = models.FileField(upload_to=get_user_video_folder)
    views = models.PositiveIntegerField(default=0)
    likes = models.ManyToManyField(Profile, blank=True, related_name='video_liked_by')

    def __str__(self):
        return f'{self.user} {self.description} {self.posted_on} video {self.views}'


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    comment_body = models.CharField(max_length=250)
    posted_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} {self.comment_body} {self.posted_on}'

    class Meta:
        abstract = True


class ImageComment(Comment):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)


class VideoComment(Comment):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)


class Statistics(models.Model):
    image_amount = models.PositiveIntegerField()
    video_amount = models.PositiveIntegerField()
    video_view_amount = models.PositiveIntegerField()
    like_amount = models.PositiveIntegerField()
    user_amount = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Date: {self.date}  Images - {self.image_amount}; Videos - {self.video_amount}; Users - {self.user_amount}'

user_profile/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Profile(AbstractUser):
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False, blank=True)
    bio = models.CharField(max_length=200, blank=True)
    vk_page = models.URLField(max_length=200, blank=True)
    email = models.EmailField('email address')

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('core:to_profile', args=[self.username])


class UserToken(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    token = models.CharField(max_length=150)

core/forms.py
from crispy_forms.bootstrap import PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field
from django import forms
from django.forms import ModelForm

from core.models import Image


class ImageUploadForm(ModelForm):
    hashtag = forms.CharField(required=False)
    place = forms.CharField(required=False)

    class Meta:
        model = Image
        fields = ['description', 'image_obj']
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_method = 'post'

core/templates/core/feed.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    {% for post in posts %}
        <div class="feed_image_wrapper border p-2 shadow rounded my-5">
            {# Post author #}
            <p class="mx-2">
                <a class="text-dark" href="{{ post.user.get_absolute_url }}">
                    {{ post.user }}</a>
            </p>

            {# Image, Video #}
            {% include 'core/includes/feed_post_object.html' %}


            {# Likes #}
            {% include 'core/includes/feed_likes.html' %}


            {# Comment image #}
            {% if post.image_obj %}
                <a href="{% url 'core:to_image' post.pk %}">
                    <img class="img_post_comment mx-2" src="{% static 'core/img/feed/comment.png' %}" alt="">
                </a>
            {% else %}
                <a href="{% url 'core:to_video' post.pk %}">
                    <img class="img_post_comment mx-2" src="{% static 'core/img/feed/comment.png' %}" alt="">
                </a>
            {% endif %}

            {# Amount likes #}
            <p class="mx-2 likes my-1">Likes: <span
                    id="likes_count_{{ post.id }}">{{ post.likes.all.count }}</span></p>

            {# Views for video #}
            {% if post.video_obj %}
                <p class="mx-2 my-1">Views: <span
                        id="views_count_{{ post.id }}">{{ post.views }}</span></p>
            {% endif %}

            {# Posted on #}
            <p class="font-weight-light mx-2 text-uppercase feed_time_text">{{ post.posted_on|timesince }}
                ago</p>

            {#  Description  #}
            {% if post.description %}
                <h6 class="mx-3">Description</h6>
                <p class="mx-4 text-dark">
                    <a href="{% url 'core:to_profile' post.user.username %}"><span
                            class="font-weight-bold">{{ post.user }}:</span></a>
                    {{ post.description }} </p>
                <hr/>
            {% endif %}

            {#  post hashtag  #}
            {% if post.hashtag %}
                <h6 class="mx-3">Hashtag</h6>
                <a href="{% url 'core:hashtag' hashtag=post.hashtag %}" class="my-1"><p
                        class="mx-4 text-dark my-1">#{{ post.hashtag }}</p></a>
                <hr/>
            {% endif %}

            {# post place  #}
            {% if post.place %}
                <h6 class="mx-3">Place</h6>
                <a href="{% url 'core:place' place_slug=post.place.place_slug %}" class="my-1"><p
                        class="mx-4 text-dark my-1">{{ post.place.place_name }}</p></a>
                <hr/>
            {% endif %}

            {#  Comments  #}
            {% include 'core/includes/feed_post_comments.html' %}


            {% if post.image_obj %}
                <div class="new_user_comments" data-pk="{{ post.id }}" data-type="Image">
                </div>
            {% else %}
                <div class="new_user_comments" data-pk="{{ post.id }}" data-type="Video">
                </div>
            {% endif %}

            {#  Add comment form  #}
            {% include 'core/includes/feed_comment_form.html' %}
        </div>




    {% endfor %}
    {#    <script src="{% static 'core/js/like-ajax.js' %}"></script>#}
    <script>
        $(document).ready(function () {
            // CSRF code
            {% include 'core/includes/ajax_setup.html' %}

            $('.img_post').click(function (e) {
                e.preventDefault();
                let data = $(this).attr("data-pk");
                let type = $(this).attr("data-type");

                $.ajax({
                    url: '{% url 'core:like' %}',
                    method: 'POST',

                    data: {
                        'post_id': data,
                        'post_type': type
                    },
                    success: function (d) {
                        let new_like = d['likes'];
                        let like_id = '#likes_count_' + data;
                        let old = $(like_id).text();
                        let img = jQuery(".img_post[data-pk='" + data + "'][data-type='" + type + "']");

                        if (old > new_like) {
                            $(img).attr('src', '{% static 'core/img/feed/like.png' %}');
                        } else {
                            $(img).attr('src', '{% static 'core/img/feed/liked.png' %}');

                        }

                        $(like_id).text(new_like);
                    },
                    error: function (d) {
                    }
                });
            });

            $('.post_comment').click(function (e) {
                e.preventDefault();
                let data = $(this).attr("data-pk");
                let type = $(this).attr("data-type");
                let comment_body = $('#add_comment_input_' + type + '_' + data).val();
                if (comment_body !== '') {
                    $('#add_comment_input_' + type + '_' + data).val('');
                    $.ajax({
                        url: '{% url 'core:comment' %}',
                        method: 'POST',

                        data: {
                            'post_comment_body': comment_body,
                            'post_id': data,
                            'post_type': type
                        },
                        success: function (d) {
                            let message = d['message'];
                            let place_to_post = jQuery(".new_user_comments[data-pk='" + data + "'][data-type='" + type + "']");
                            if (message === 'OK') {
                                place_to_post.append('<p class="mx-4 text-dark my-1">' +
                                    '<span class="font-weight-bold">{{ request.user }}:</span> ' +
                                    comment_body + '</p>');
                            }
                        },
                        error: function (d) {
                        }
                    });
                }
            });

            $('.video').click(function (e) {
                    e.preventDefault();

                    let data = $(this).attr("data-pk");
                    let vid = $(".video[data-pk='" + data + "']").get(0);
                    if (vid.paused) {
                        vid.play();
                        $.ajax({
                            url: '{% url 'core:add_view' %}',
                            method: 'POST',

                            data: {
                                'video_pk': data
                            },
                            success: function (d) {
                                let new_views = d['views'];
                                let views_count = $('#views_count_' + data);

                                $(views_count).text(new_views);
                            },
                            error: function (d) {
                            }
                        });
                    } else {
                        vid.pause();
                    }
                }
            );


        });
    </script>

{% endblock %}

core/templates/core/followers.html
{% extends "core/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <a href="{% url 'core:to_profile' profile.username %}" class="text-dark">
                <h2>{{ profile.username }}</h2>
            </a>
            <h3 class="font-weight-light">{{ profile.first_name }} {{ profile.last_name }}</h3>
            <h3 class="font-weight-light">Followers: </h3>
            <br>

            {% for profile_follower in profile_list %}
                <div class="shadow rounded mb-4 p-3 row col">
                    <div class="col">
                        <a href="{% url 'core:to_profile' profile_follower.username %}" class="text-dark">

                            <h2>{{ profile_follower.username }}</h2>
                        </a>
                        <h3 class="font-weight-light">{{ profile_follower.first_name }} {{ profile_follower.last_name }}</h3>
                    </div>

                    <div class="col-3 text-center">
                        {% if profile == request.user %}
                            {% if profile_follower not in user.follows.all %}
                                <button class="follow btn btn-outline-success my-2"
                                        data-username="{{ profile_follower.username }}">
                                    Follow
                                </button>
                                <a href="{% url 'messages:write_to' profile_follower.username %}"
                                   class="btn btn-outline-success float-right">Write
                                    message</a>
                            {% else %}
                                <button class="follow btn btn-outline-danger my-2"
                                        data-username="{{ profile_follower.username }}">
                                    Unfollow
                                </button>
                                <a href="{% url 'messages:write_to' profile_follower.username %}"
                                   class="btn btn-outline-success float-right">Write
                                    message</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}


            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
    </span>
            </div>

        </div>
    </div>

    <script>

        $(document).ready(function () {
            // CSRF code
            {% include 'core/includes/ajax_setup.html' %}

            function change_button_to_unfollow(username) {
                let follow_btn = jQuery(".follow[data-username='" + username + "']");
                {# color  #}
                follow_btn.removeClass('btn-outline-success').addClass('btn-outline-danger');
                {# value #}
                follow_btn.text('Unfollow')
            }

            function change_button_to_follow(username) {
                let follow_btn = jQuery(".follow[data-username='" + username + "']");
                {# color  #}
                follow_btn.removeClass('btn-outline-danger').addClass('btn-outline-success');
                {# value #}
                follow_btn.text('Follow')
            }

            $('.follow').click(function (e) {
                e.preventDefault();
                let data = $(this).attr("data-username");

                $.ajax({
                    url: '{% url 'core:follow' %}',
                    method: 'POST',

                    data: {
                        'username': data
                    },
                    success: function (d) {
                        let message = d['status'];
                        if (message === 'Removed') {
                            change_button_to_follow(data);
                        } else if (message === 'Added') {
                            change_button_to_unfollow(data)
                        }
                    },
                    error: function (d) {
                    }
                });
            });


        });
    </script>
{% endblock %}

core/templates/core/header.html
<header>
    {#    {% block login %}#}
    <div class="header_pos d-flex flex-column flex-md-row fixed-top align-items-center p-2 px-md-3 mb-2 bg-white border-bottom shadow-sm">
        <a class="my-0 mr-md-auto navbar-brand text-dark" href="{% url 'core:feed' %}">Instagram</a>
        <nav class="my-2 my-md-0 mr-md-3">
            {% if user.is_authenticated %}
                <a href="{% url 'core:add_image' %}" class="btn btn-outline-success mr-2">Add image</a>
                <a href="{% url 'messages:chats' %}" class="btn btn-outline-primary mr-2">Chat</a>
                <a href="{% url 'core:to_profile' request.user %}" class="mr-2">My Profile ({{ user.username }})</a>
                <a href="{% url 'user_profile:logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'user_profile:login' %}" class="mr-2">Login</a>
                <a href="{% url 'user_profile:registration' %}">Register</a>
            {% endif %}
        </nav>
    </div>
</header>

core/templates/core/image_detail.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="feed_image_wrapper border p-2 m-4 shadow rounded my-5 col">

            {# Image #}
            <div class="my-2">
                <a href="">
                    <img class="image_profile img-thumbnail" src="{{ object.image_obj.url }}" alt="">
                </a>
            </div>


            {#  Description  #}
            <div>

                {% if object.description %}
                    <h5 class="mx-3">Description</h5>
                    <p class="mx-4 text-dark">
                        <a href="{% url 'core:to_profile' object.user.username %}"><span
                                class="font-weight-bold">{{ object.user }}:</span></a>
                        {{ object.description }} </p>
                    <hr/>
                {% endif %}
            </div>
            <div>
                {% if object.hashtag %}
                    <h5 class="mx-3">Hashtag</h5>
                    <a href="{% url 'core:hashtag' hashtag=object.hashtag %}" class="my-1"><p
                            class="mx-4 text-dark my-1">#{{ object.hashtag }}</p></a>
                    <hr/>
                {% endif %}
            </div>
            <div>
                {% if object.place %}
                    <h5 class="mx-3">Place</h5>
                    <a href="{% url 'core:place' object.place.place_slug %}" class="my-1"><p
                            class="mx-4 text-dark my-1">{{ object.place.place_name }}</p></a>
                    <hr/>
                {% endif %}
            </div>
        </div>
        <div class="border p-2 m-4 shadow rounded my-5 col-4 d-flex flex-column">
            {# Post author #}
            <div>
                <h4 class="mx-2">Author</h4>
                <p class="mx-4">
                    <a class="text-dark" href="{{ object.user.get_absolute_url }}">
                        {{ object.user }}</a>
                    <a href="{% url 'core:to_profile_followers' object.user.username %}">{{ subs_amount }} subs</a>
                </p>
                <hr/>
            </div>
            {#  Comments  #}
            <div>
                <h4 class="mx-2">Comments</h4>
                {% for comment in post_comments %}
                    <p class="mx-4 text-dark my-2">
                        <a href="{% url 'core:to_profile' comment.user.username %}"><span
                                class="font-weight-bold">{{ comment.user }}:</span></a>
                        {{ comment.comment_body }} ({{ comment.posted_on|timesince }} ago)</p>
                {% endfor %}
                {# Go to full comment page #}
                {% if post_comments %}
                    <a href="{% url 'core:image_comments' object.pk %}" class="mx-4">Show all comments...</a>
                    <hr/>
                {% endif %}
            </div>

            <div class="new_user_comments" data-pk="{{ object.id }}" data-type="Image">
            </div>

            {# align to the bottom of block #}
            <div class="mt-auto">
                <hr/>
                {# Likes #}
                {% if request.user in object.likes.all %}
                    <img class="img_post" data-pk="{{ object.id }}" data-type="Image"
                         src="{% static  'core/img/feed/liked.png' %}"
                         alt="">
                {% else %}
                    <img class="img_post" data-pk="{{ object.id }}" data-type="Image"
                         src="{% static  'core/img/feed/like.png' %}"
                         alt="">
                {% endif %}

                {# Comment image #}
                <a href="{% url 'core:to_image' object.pk %}">
                    <img class="img_post_comment mx-2" src="{% static 'core/img/feed/comment.png' %}" alt="">
                </a>

                {# Amount likes #}
                <p class="mx-2 likes my-1">Likes: <span
                        id="likes_count_{{ object.id }}">{{ object.likes.all.count }}</span></p>

                {# Posted on #}

                <p class="font-weight-light mx-2 text-uppercase feed_time_text">{{ object.posted_on|timesince }}
                    ago</p>


                {#  Add comment form  #}
                <form class="my-2">
                    <div class="row">
                        <div class="col">
                            <input id="add_comment_input_Image_{{ object.id }}" name="add_comment_input" type="text"
                                   class="form-control feed_comment_block"
                                   placeholder="Add a comment">
                        </div>
                        <div class="col-3">
                            <button class="btn post_comment" data-pk="{{ object.id }}" data-type="Image">Post</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>


    </div>

    {#    <script src="{% static 'core/js/like-ajax.js' %}"></script>#}
    <script>
        $(document).ready(function () {
            // CSRF code
            {% include 'core/includes/ajax_setup.html' %}

            $('.img_post').click(function (e) {
                e.preventDefault();
                let data = $(this).attr("data-pk");
                let type = $(this).attr("data-type");

                $.ajax({
                    url: '{% url 'core:like' %}',
                    method: 'POST',

                    data: {
                        'post_id': data,
                        'post_type': type
                    },
                    success: function (d) {
                        let new_like = d['likes'];
                        let like_id = '#likes_count_' + data;
                        let old = $(like_id).text();
                        let img = jQuery(".img_post[data-pk='" + data + "'][data-type='" + type + "']");

                        if (old > new_like) {
                            $(img).attr('src', '{% static 'core/img/feed/like.png' %}');
                        } else {
                            $(img).attr('src', '{% static 'core/img/feed/liked.png' %}');

                        }

                        $(like_id).text(new_like);
                    },
                    error: function (d) {
                    }
                });
            });

            $('.post_comment').click(function (e) {
                e.preventDefault();
                let data = $(this).attr("data-pk");
                let type = $(this).attr("data-type");
                let comment_body = $('#add_comment_input_' + type + '_' + data).val();
                if (comment_body !== '') {
                    $('#add_comment_input_' + type + '_' + data).val('');
                    $.ajax({
                        url: '{% url 'core:comment' %}',
                        method: 'POST',

                        data: {
                            'post_comment_body': comment_body,
                            'post_id': data,
                            'post_type': type
                        },
                        success: function (d) {
                            let message = d['message'];
                            let place_to_post = jQuery(".new_user_comments[data-pk='" + data + "'][data-type='" + type + "']");
                            if (message === 'OK') {
                                place_to_post.append('<p class="mx-4 text-dark my-1">' +
                                    '<span class="font-weight-bold">{{ request.user }}:</span> ' +
                                    comment_body + '</p>');
                            }
                        },
                        error: function (d) {
                        }
                    });
                }
            });

        });
    </script>

{% endblock %}

core/templates/core/profile_detail.html
{% extends "core/base.html" %}
{% load humanize %}

{% block content %}
    {% if profile == request.user %}
        <h1>Hi, {{ profile.username }}</h1>
    {% else %}
        <h1>{{ profile.username }}</h1>
        <a href="{% url 'messages:write_to' profile.username %}"
           class="btn btn-outline-success float-right">Write
            message</a>
    {% endif %}
    <h3 class="font-weight-light">{{ profile.first_name }} {{ profile.last_name }}</h3>
    <h3 class="font-weight-light">Bio: {{ profile.bio }}</h3>
    <a class="btn btn-outline-dark my-3" href="{% url 'core:to_profile_followers' profile.username %}">
        Followers: {{ followers_amount|intcomma }}
    </a>

    <h3>Your images:</h3>
    <div class="content_wrapper">
        {% for user_image in user_images %}
            <div class="content_block">
                <a href="{% url 'core:to_image' user_image.pk %}">
                    <img class="image_profile img-thumbnail" src="{{ user_image.image_obj.url }}" alt="">
                </a>
                <p>Likes: {{ user_image.likes.count }}</p>

            </div>
        {% endfor %}
    </div>

    <h3>Your videos:</h3>
    <div class="content_wrapper">
        {% for user_video in user_videos %}
            <div class="content_block">
                <div class="img-thumbnail embed-responsive embed-responsive-16by9">
                    <video controls>
                        <source src="{{ user_video.video_obj.url }}">
                    </video>
                </div>
                <a href="{% url 'core:to_video' user_video.pk %}">
                    Go to post
                </a>
                <p class="m-1">Likes: {{ user_video.likes.count }}</p>
                <p class="m-1">Views: {{ user_video.views }}</p>

            </div>
        {% endfor %}


    </div>

{% endblock %}