core/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path

from core.views import ProfileDetailView, FeedView, LikeView, CommentView, FollowersView, FollowView, ImageDetailView, \
    VideoDetailView, AddViewsToVideo, HashTagPostListView, PlacePostListView, ImageCommentsView, AddImageView

app_name = 'core'
urlpatterns = [
    path('', FeedView.as_view(), name='feed'),
    path('profile/<username>', ProfileDetailView.as_view(), name='to_profile'),
    path('profile/<username>/followers', FollowersView.as_view(), name='to_profile_followers'),
    path('like/', LikeView.as_view(), name='like'),
    path('follow/', FollowView.as_view(), name='follow'),
    path('comment/', CommentView.as_view(), name='comment'),
    path('image/<int:pk>', ImageDetailView.as_view(), name='to_image'),
    path('video/<int:pk>', VideoDetailView.as_view(), name='to_video'),
    path('add_view/', AddViewsToVideo.as_view(), name='add_view'),
    path('hashtag/<hashtag>', HashTagPostListView.as_view(), name='hashtag'),
    path('place/<place_slug>', PlacePostListView.as_view(), name='place'),
    path('image/<int:pk>/comments', ImageCommentsView.as_view(), name='image_comments'),
    path('add/image', AddImageView.as_view(), name='add_image'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

instagram_clone_django/urls.py
from django.conf.urls import url
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, include

import core

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Api descriotion",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('message.urls')),
    path('', include('core.urls')),
    path('auth/', include('user_profile.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

handler404 = core.views.error_404
handler500 = core.views.error_500

message/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from message.api import MessageViewSet, ChatViewSet
from message.views import RoomView, RoomListView, CreateChatRoom

app_name = 'messages'

router = DefaultRouter()
router.register(r'messages', MessageViewSet, basename='message')
router.register(r'chatroom', ChatViewSet, basename='chatroom')

urlpatterns = [
    path('chats/', RoomListView.as_view(), name='chats'),
    path('<int:id>/', RoomView.as_view(), name='room'),
    path('api/', include(router.urls)),
    path('write/<username>/', CreateChatRoom.as_view(), name='write_to')
]

message/models.py
from django.db import models

# Create your models here.
from user_profile.models import Profile


class ChatRoom(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, 'Dialog'),
        (CHAT, 'Chat')
    )

    type = models.CharField(
        max_length=1,
        choices=CHAT_TYPE_CHOICES,
        default=DIALOG
    )
    members = models.ManyToManyField(Profile)

    def __str__(self):
        return f'Type: {self.type} Members: {self.members.count()}'


class Message(models.Model):
    text = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    chat = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    is_readed = models.BooleanField(default=False)

    class Meta:
        ordering = ['time']

    def __str__(self):
        return f'{self.author} - {self.text} ({self.time})'

message/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView, ListView

from message.models import ChatRoom, Message
from user_profile.models import Profile


class ChatAccessMixin(AccessMixin):
    """Verify that the current user is member of chat."""

    def dispatch(self, request, *args, **kwargs):
        chat = ChatRoom.objects.get(id=request.kwargs['id'])
        if not request.user.is_authenticated and request.user not in chat.members:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class RoomView(TemplateView, ChatAccessMixin):
    template_name = 'message/dialog.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        room_id = self.kwargs['id']
        ctx['room_id'] = room_id

        messages = Message.objects.filter(chat_id=room_id)[:10]
        ctx['messages'] = messages

        chat = ChatRoom.objects.get(id=room_id)
        ctx['chat'] = chat
        return ctx


class RoomListView(ListView, LoginRequiredMixin):
    template_name = 'message/chat_list.html'
    model = ChatRoom

    def get_queryset(self):
        queryset = ChatRoom.objects.filter(members__username=self.request.user.username)
        return queryset


class CreateChatRoom(TemplateView, LoginRequiredMixin):

    def get(self, request, *args, **kwargs):
        target_user = Profile.objects.get(username=kwargs['username'])

        # Chats with current user and target user
        chats = ChatRoom.objects.filter(members__username__in=[request.user]).filter(
            members__username__in=[target_user]).filter(type=ChatRoom.DIALOG)

        chat_d = chats.first()
        if not chat_d:
            chat_d = ChatRoom.objects.create()
            chat_d.type = ChatRoom.DIALOG
            chat_d.members.add(target_user, request.user)
            chat_d.save()

        return HttpResponseRedirect(reverse('messages:room', args=[chat_d.pk]))

message/templates/message/chat_list.html
{% extends 'core/base.html' %}

{% block title %}
    Chat List
{% endblock %}

{% block content %}
    <div class="col-8 offset-2 shadow" style="height: 35em; overflow: auto;">
        <h2 class="font-weight-light p-2">Chats
            <a href="{% url 'core:to_profile_followers' request.user.username %}"
               class="btn btn-outline-dark float-right">
                Create</a>
        </h2>
        <hr/>
        {% for chat in object_list %}
            <div class="py-2">
                {% if chat.type == chat.DIALOG %}
                    <h3><span class="font-weight-light">Dialog: </span>
                        {% for member in chat.members.all %}
                            {% if member != request.user %}
                                <a href="{% url 'core:to_profile'  member.username %}" class="text-dark">
                                    {{ member.username }}
                                </a>
                                <a href="{% url 'messages:room' chat.id %}" class="btn btn-outline-success float-right">Write
                                    message</a>
                            {% endif %}
                        {% endfor %}
                    </h3>
                {% else %}
                    <h3><span class="font-weight-light">Chat: </span> <a href="">{{ chat.members.all.count }}
                        members</a>
                        <a href="{% url 'messages:room' chat.id %}" class="btn btn-outline-success float-right">Write
                            message</a>
                    </h3>


                {% endif %}


            </div>
        {% endfor %}

    </div>

{% endblock %}

message/templates/message/dialog.html
{% extends 'core/base.html' %}

{% block title %}
    Chat room
{% endblock %}

{% block content %}
    <div class="col-8 offset-2 shadow mh-100">
        <div class="pt-2">
            {% if chat.type == chat.DIALOG %}
                <h3>Dialog with:
                    {% for member in chat.members.all %}
                        {% if member != request.user %}
                            <a href="{% url 'core:to_profile'  member.username %}">
                                {{ member.username }}
                            </a>
                        {% endif %}
                    {% endfor %}
                </h3>
            {% else %}
                <h3>Chat with: <a href="">{{ chat.members.all.count }} members</a></h3>
            {% endif %}
        </div>
        <hr>
        <div style="height: 35em; overflow: auto;">
            {% if messages.count == 0 %}
                <p class="msg"></p>
            {% endif %}
            {% for message in messages %}
                <div class="row mx-3 msg">
                    <p class="m-2 border {% if message.author == request.user %}
                    border-primary {% else %}border-warning
                    {% endif %} rounded-lg p-2">
                        <a href="{% url 'core:to_profile'  message.author.username %}">
                            {{ message.author.username }}:
                        </a>
                        <br>
                        <span class="">
                                {{ message.text }}
                                <span class="font-weight-light">{{ message.time.time }}</span>
                            </span>
                    </p>
                </div>
            {% endfor %}

        </div>
        {# align to the bottom of block #}
        <div class="mt-auto pb-2">
            <hr/>


            <div class="row">
                <div class="col-10">
                    <input id="chat-message-input" type="text"
                           class="form-control feed_comment_block"
                           placeholder="Write message"/>
                </div>
                <div class="col">
                    <input id="chat-message-submit" class="btn btn-outline-dark" type="button" value="Send"/>
                </div>
            </div>

        </div>
    </div>


    {{ room_id|json_script:"room-id" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-id').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            let last_div = $('.msg').last();
            let message_div = $('<div>', {class: "row mx-3 msg"}).insertAfter(last_div);
            let message_text = $('<p>', {class: "m-2 border p-2 rounded", text: data.message});
            let currentUsername = "{{ request.user.username }}";
            let to_profile_link = $('<a>', {href: '', text: data.username + ':'});

            if (currentUsername == data.username) {
                message_text.addClass('border-primary');
            } else {
                message_text.addClass('border-warning');
            }
            message_div.append(message_text);
            message_text.prepend($('<br>'));
            message_text.prepend(to_profile_link);
            message_text.append($('<span>', {class: 'font-weight-light', text: ' ' + data.time}))


        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            let username = "{{ request.user.username}}";
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': username,
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock %}